name: Test
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create and upload image
      uses: ./
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ecr_registry: ${{ secrets.ECR_REGISTRY }}
        region: us-east-1
        repo: ${{ github.repository }}
        tags: dev-${{ github.run_number }}
